server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: validator-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: INFO
    com.ksoft.validator: DEBUG